### PR TITLE
Add Ramayan

### PR DESCRIPTION
**Pull request by aviskarkc10**
Probably going to hell for this, but fuck it!

### CODE REVIEW

**Comment by mesaugat** [comment]
This is not going to be merged unless you do it yourself. Too forced for my liking.

**Comment by aviskarkc10** [comment]
:sob:

**Comment by aviskarkc10** [comment]
@mesaugat you can close it if it's too forced

**Comment by mesaugat** [comment]
Can re-open if someone else thinks differently.

**Pull request closed without merging**
